version: "3"
services:
  kafka:
    image: kafka
    build:
      context: .
      dockerfile: ./dockers/kafka/Dockerfile
    container_name: kafka
    restart: always
    environment:
      KAFKA_CREATE_TOPICS: "flight_delay_classification_request:1:1"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - 9092:9092
    depends_on:
      - zookeeper
    networks:
      - bdfi
  zookeeper:
    image: zookeeper
    build:
      context: .
      dockerfile: ./dockers/zookeeper/Dockerfile
    container_name: zookeeper
    restart: always
    ports:
      - 2181:2181
    networks:
      - bdfi
  mongo:
    image: mongo
    hostname: mongo
    build:
      context: .
      dockerfile: ./dockers/mongo/Dockerfile
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    networks:
      - bdfi
  master:
    image: bitnami/spark:3.1.2
    container_name: master
    hostname: master
    restart: always
    ports:
      - 8080:8080
      - 7077:7077
    environment:
      SPARK_MODE: master
    networks:
      - bdfi
    volumes:
      - ./models:/models
  worker:
    image: bitnami/spark:3.1.2
    restart: always
    deploy:
      replicas: 3
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://master:7077
    depends_on:
      - master
    networks:
      - bdfi
    volumes:
      - ./models:/models
      - ./resources:/resources
      - ./data:/practica_big_data_2019/data
      - ./models:/practica_big_data_2019/models
  web:
    image: web
    build:
      context: .
      dockerfile: ./dockers/web/Dockerfile
    container_name: web
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - mongo
      - spark
    networks:
      - bdfi
  spark:
    image: spark
    build:
      context: .
      dockerfile: ./dockers/spark/Dockerfile
    container_name: spark
    restart: always
    depends_on:
      - mongo
      - master
      - kafka
    networks:
      - bdfi
    volumes:
      - ./models:/models
  airflow:
    image: airflow
    build:
      context: .
      dockerfile: ./dockers/airflow/Dockerfile
    container_name: airflow
    restart: always
    ports:
      - 9090:9090
    depends_on:
      - master
    networks:
      - bdfi
networks:
  bdfi:
volumes:
  models:
  resources: